window.SENTRAN_STATUS_EQUIPAMENTOS = {
  "gerado_em": "2026-05-31T02:08:13",
  "fonte": "Relatório 8 SPLTV",
  "total": 26,
  "equipamentos": [
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-819",
      "equipamento": "819",
      "ip": "HTTP://10.20.30.18:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "OK",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-820",
      "equipamento": "820",
      "ip": "HTTP://10.20.30.14:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-821",
      "equipamento": "821",
      "ip": "HTTP://10.20.30.86:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-822",
      "equipamento": "822",
      "ip": "HTTP://10.20.30.54:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-823",
      "equipamento": "823",
      "ip": "HTTP://10.20.30.158:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-824",
      "equipamento": "824",
      "ip": "HTTP://10.20.30.222:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "OK",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-825",
      "equipamento": "825",
      "ip": "HTTP://10.20.30.42:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "OK",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-826",
      "equipamento": "826",
      "ip": "HTTP://10.20.30.6:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "OK",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-827",
      "equipamento": "827",
      "ip": "HTTP://10.20.30.70:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-828",
      "equipamento": "828",
      "ip": "HTTP://10.20.30.62:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-829",
      "equipamento": "829",
      "ip": "HTTP://10.20.30.58:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-830",
      "equipamento": "830",
      "ip": "HTTP://10.20.30.122:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-831",
      "equipamento": "831",
      "ip": "HTTP://10.20.30.34:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-832",
      "equipamento": "832",
      "ip": "HTTP://10.20.30.26:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-833",
      "equipamento": "833",
      "ip": "HTTP://10.20.30.138:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-834",
      "equipamento": "834",
      "ip": "HTTP://10.20.30.82:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "-",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-835",
      "equipamento": "835",
      "ip": "HTTP://10.20.30.22:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-848",
      "equipamento": "848",
      "ip": "HTTP://10.20.30.78:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "OK",
      "parada": "OK",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-849",
      "equipamento": "849",
      "ip": "HTTP://10.20.30.30:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "OK",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-850",
      "equipamento": "850",
      "ip": "HTTP://10.20.30.50:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "-",
      "avanco": "OK",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-851",
      "equipamento": "851",
      "ip": "HTTP://10.20.30.10:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "-",
      "avanco": "OK",
      "parada": "OK",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-1734",
      "equipamento": "1734",
      "ip": "HTTP://10.20.30.38:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "-",
      "avanco": "OK",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-1878",
      "equipamento": "1878",
      "ip": "HTTP://10.20.30.106:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "-",
      "avanco": "OK",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-1879",
      "equipamento": "1879",
      "ip": "HTTP://10.20.30.102:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-1880",
      "equipamento": "1880",
      "ip": "HTTP://10.20.30.90:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "-",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    },
    {
      "contrato": "Amparo",
      "serie": "SPLAMP-1881",
      "equipamento": "1881",
      "ip": "HTTP://10.20.30.94:8989",
      "status": "offline",
      "status_relatorio": "OFF",
      "trafego": "OK",
      "velocidade": "OK",
      "avanco": "OK",
      "parada": "-",
      "local_horario": "-",
      "prova": "-",
      "teste": "-",
      "ultima_atualizacao": "2026-05-31T02:08:13",
      "origem": "relatorio_8_atual.xlsx"
    }
  ]
};
